services:
  # A web service with Flask
  - type: web
    name: ai-vision-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-vision-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  # Create a PostgreSQL database
  - name: ai-vision-db
    databaseName: ai_vision
    plan: free

# Static files can be served directly by Render
staticSites:
  - name: ai-vision-static
    buildCommand: echo "No build required for static assets"
    publishDir: static
    pullRequestPreviewsEnabled: false