services:
  # A web service with Flask
  - type: web
    name: ai-vision-detection
    env: python
    buildCommand: ./render_build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers=1 --threads=8 --timeout=120 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: ai-vision-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
